/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package display;

import engine.GamePanel;

/**
 *
 * @author alisson
 */
public class GameOver extends javax.swing.JPanel {

    
    GamePanel gp ;
    Window gameWindow;
    /**
     * Creates new form GameOver
     */
    public GameOver(GamePanel gp ) {
        this.gp = gp;
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    
    private void initComponents() {
        
        
        
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        ExitButton = new javax.swing.JButton();
        NewGameButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 102, 102));
        setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));

        jScrollPane1.setFocusable(false);

        jTextPane1.setEditable(false);
        jTextPane1.setBackground(new java.awt.Color(0, 0, 0));
        jTextPane1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 1, 1, new java.awt.Color(255, 255, 255)));
        jTextPane1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jTextPane1.setForeground(new java.awt.Color(0, 204, 0));
        jTextPane1.setText("                           Alas! Brave Adventurer.\n                         You have met a Sad Fate.\n                                But do not despair,\n              For gods will bring you back into the world...\n                      In exchange for a small sacrifice...\n                       Click in New Game for play Again.\n           Click on Quit to leave humanity on Zenith's hands.");
        jTextPane1.setToolTipText("");
        jTextPane1.setMargin(new java.awt.Insets(5, 4, 3, 3));
        jTextPane1.setName(""); // NOI18N
        jTextPane1.setSelectionColor(new java.awt.Color(255, 0, 0));
        jScrollPane1.setViewportView(jTextPane1);

        ExitButton.setBackground(new java.awt.Color(102, 102, 102));
        ExitButton.setFont(new java.awt.Font("Maiandra GD", 0, 36)); // NOI18N
        ExitButton.setForeground(new java.awt.Color(255, 0, 0));
        ExitButton.setText("I WANT TO QUIT");
        ExitButton.setToolTipText("I am too weak for this.");
        ExitButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 51, 0)));
        ExitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        NewGameButton.setBackground(new java.awt.Color(102, 102, 102));
        NewGameButton.setFont(new java.awt.Font("Maiandra GD", 0, 48)); // NOI18N
        NewGameButton.setForeground(new java.awt.Color(0, 153, 0));
        NewGameButton.setText("NEW GAME");
        NewGameButton.setToolTipText("I want to Save the World!");
        NewGameButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 255, 0)));
        NewGameButton.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        NewGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewGameButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NewGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(350, 350, 350)
                        .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1028, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        this.setLayout(layout);
        this.doLayout();

        ExitButton.getAccessibleContext().setAccessibleDescription("I'm too weak to play this.");
        
        
        
        
    }// </editor-fold>                        
//initializes the components for this frame
    
    private void NewGameButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        
        
        System.out.println("We fight for a better world!");
        this.gp.window.frame.dispose();
        this.gp.deathMusic.stop();
        this.gp = new GamePanel();
        
        
        
    }                                             
//the function event for when the button is clicked
    
    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        
        System.out.println("I expected more from you!!!");
        System.exit(0);
        
        
     
        
    }                                          
//the function event for when the button is clicked
    
    // Variables declaration - do not modify                     
    private javax.swing.JButton ExitButton;
    private javax.swing.JButton NewGameButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration                   
}
